### PR TITLE
Updating stats

### PR DESCRIPTION
**Pull request by gq1**
I have updated all the stats updating scripts and this will affect the following pages:

Pipeline stats:
http://pipelines.tol-dev.sanger.ac.uk/genomenote/releases_stats

Modules and pipeline relationship:
http://pipelines.tol-dev.sanger.ac.uk/modules
http://pipelines.tol-dev.sanger.ac.uk/modules/samtools_markdup

Overall stats:
http://pipelines.tol-dev.sanger.ac.uk/stats

Community:
http://pipelines.tol-dev.sanger.ac.uk/community

Schema builder:
http://pipelines.tol-dev.sanger.ac.uk/pipeline_schema_builder

The contents of the last 3 pages may need more work.

### CODE REVIEW

**Comment by muffato** [comment]
Just pushed some minor updates to 1) move the charts to different columns, 2) change the start date

**Comment by priyanka-surana** [comment]
I am going to deploy this branch on the dev version so I can visualise the changes needed.

**Comment by priyanka-surana** [comment]
When I run `prettier -w .` in this branch nothing actually happens. I am merging this into `main`. Any issues let me know.

@gq1 We have to create a new PR to add some core repos and test that out.

**Comment by gq1** [comment]
@priyanka-surana 
This is my first time to run `prettier` here and also first time for the Github workflow working.

I committed the fixes and most of them are white spaces. You may need to check the affected pages again.

I tried both version 2.4.1 and 2.8.8, no format problems but got lots of warnings like in Github actions.
Do you have this problem?
```
[warn] Ignored unknown option { braceStyle: "1tbs" }.
[warn] Ignored unknown option { phpVersion: "7.4" }.
```

I will try again today and also will fix the Github fixing linting workflow.

**Comment by gq1** [comment]
@priyanka-surana @muffato 

I also fix the launch button for pipelines. Not sure this is useful for not. 
http://pipelines.tol-dev.sanger.ac.uk/genomenote
If we want to keep it, we need add one more flag to point to our url for `nf-core` command.

I also noticed some pipelines don't have the launch button instead of See button. I will check why.
http://pipelines.tol-dev.sanger.ac.uk/sequencecomposition




I noticed some pip

**Comment by gq1** [comment]
> Yes I got loads of these warnings too. Never had anything like this with the pipelines.
nf-core doesn't have these warnings, the code is the same.
I will check more later.
> 
> Which files did you update? I cannot see any new commits in `main`.
I meant this commit, not to the main but in main now.
https://github.com/sanger-tol/pipelines-website/pull/32/commits/fae169f5958107ed9a317c72643bef59eba014ec

**Pull request merged**
