### PR TITLE
Pull from nf-core

### PR DESCRIPTION
**Pull request by priyanka-surana**

### CODE REVIEW

**Comment by gq1** [comment]
@priyanka-surana @muffato
Do we still want this merging? Mainly documentation and format changes, only one package change. 
They probably won't update the master branch any more.

**Comment by priyanka-surana** [comment]
This will be the last update, I am guessing. We have to go through this and make sure nothing breaks our website before merging.
There is no `master` branch anymore. It is now called `php-site-2023` and the repo is called `nf-core/website`.

**Comment by gq1** [comment]
Can we do the merging? Then we can do more tidy-up for our branch, no need to worry about any further conflicts.

**Comment by priyanka-surana** [comment]
Sure 👍🏼 Let me know if you need any help.

**Pull request merged**
